#!/usr/bin/env python3
"""
Fine-tunes a local Ollama model on SFT pairs.

Strategy A (--backend ollama-modelfile):
    Bakes training examples as MESSAGE directives into an Ollama Modelfile,
    then runs `ollama create loci-tuned -f mlops/finetune/Modelfile`.
    No GPU required.

Strategy B (--backend unsloth):
    Emits mlops/finetune/run_unsloth.py and mlops/finetune/export_gguf.sh
    for offline GPU fine-tuning via Unsloth + LoRA. Does not execute them.

Usage:
    python3 mlops/finetune/train_lora.py \
        --sft mlops/finetune/data/sft_pairs.jsonl \
        --base-model llama3.2:latest \
        --backend ollama-modelfile \
        [--max-examples 200]
"""

import argparse
import json
import os
import subprocess
import sys
import textwrap


_HERE = os.path.dirname(os.path.abspath(__file__))


# ---------------------------------------------------------------------------
# Shared: load SFT pairs
# ---------------------------------------------------------------------------

def load_pairs(path: str, max_examples: int) -> list[dict]:
    pairs = []
    try:
        with open(path) as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    pairs.append(json.loads(line))
                except json.JSONDecodeError:
                    continue
    except FileNotFoundError:
        print(f"[train] SFT file not found: {path}", file=sys.stderr)
        sys.exit(1)
    return pairs[:max_examples]


# ---------------------------------------------------------------------------
# Strategy A: Ollama Modelfile few-shot baking
# ---------------------------------------------------------------------------

def _escape_modelfile_value(s: str) -> str:
    # Ollama Modelfile does not support backslash escaping inside MESSAGE
    # blocks; the safest approach is to truncate at any literal triple-quote.
    return s.replace('"""', "'''")


def build_modelfile(base_model: str, pairs: list[dict]) -> str:
    lines = [f'FROM {base_model}', ""]

    lines.append(
        "SYSTEM You are Loci, an autonomous coding agent with strong memory. "
        "You learn from past failures and apply corrected reasoning."
    )
    lines.append("")

    for pair in pairs:
        messages = pair.get("messages", [])
        if len(messages) < 2:
            continue
        user_msg = _escape_modelfile_value(messages[0].get("content", ""))
        asst_msg = _escape_modelfile_value(messages[1].get("content", ""))
        lines.append(f'MESSAGE user {user_msg}')
        lines.append(f'MESSAGE assistant {asst_msg}')
        lines.append("")

    return "\n".join(lines)


def run_ollama_modelfile_backend(args: argparse.Namespace) -> None:
    pairs = load_pairs(args.sft, args.max_examples)
    if not pairs:
        print("[train] no SFT pairs loaded — nothing to bake", file=sys.stderr)
        sys.exit(1)

    modelfile_content = build_modelfile(args.base_model, pairs)
    modelfile_path = os.path.join(_HERE, "Modelfile")

    with open(modelfile_path, "w") as f:
        f.write(modelfile_content)

    print(f"[train] wrote Modelfile with {len(pairs)} examples → {modelfile_path}")

    print("[train] running: ollama create loci-tuned -f", modelfile_path)
    result = subprocess.run(
        ["ollama", "create", "loci-tuned", "-f", modelfile_path],
        capture_output=False,
    )
    if result.returncode != 0:
        print(f"[train] ollama create failed (exit {result.returncode})", file=sys.stderr)
        sys.exit(result.returncode)

    print("[train] model created. Running probe...")
    probe = subprocess.run(
        ["ollama", "run", "loci-tuned",
         "What is the most important memory about authentication?"],
        capture_output=False,
    )
    if probe.returncode != 0:
        print(f"[train] probe run failed (exit {probe.returncode})", file=sys.stderr)


# ---------------------------------------------------------------------------
# Strategy B: Unsloth script emission
# ---------------------------------------------------------------------------

_UNSLOTH_SCRIPT = '''\
#!/usr/bin/env python3
"""
Generated by train_lora.py — run this on a machine with a GPU and Unsloth installed:
    pip install unsloth
    python3 mlops/finetune/run_unsloth.py
"""
import json
from datasets import Dataset
from trl import SFTTrainer
from transformers import TrainingArguments
from unsloth import FastLanguageModel

SFT_PAIRS   = "{sft_path}"
BASE_MODEL  = "{base_model}"
OUTPUT_DIR  = "{output_dir}"
MAX_SEQ_LEN = 2048
LORA_R      = 16
LORA_ALPHA  = 16

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name=BASE_MODEL,
    max_seq_length=MAX_SEQ_LEN,
    load_in_4bit=True,
)

model = FastLanguageModel.get_peft_model(
    model,
    r=LORA_R,
    lora_alpha=LORA_ALPHA,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                    "gate_proj", "up_proj", "down_proj"],
    lora_dropout=0.05,
    bias="none",
    use_gradient_checkpointing=True,
)

raw_pairs = []
with open(SFT_PAIRS) as f:
    for line in f:
        line = line.strip()
        if line:
            raw_pairs.append(json.loads(line))

def _fmt(pair):
    msgs = pair.get("messages", [])
    text = ""
    for m in msgs:
        role = m.get("role", "")
        content = m.get("content", "")
        if role == "user":
            text += f"<|user|>\\n{{content}}\\n"
        elif role == "assistant":
            text += f"<|assistant|>\\n{{content}}\\n"
    return {{"text": text}}

dataset = Dataset.from_list([_fmt(p) for p in raw_pairs])

trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=dataset,
    dataset_text_field="text",
    max_seq_length=MAX_SEQ_LEN,
    args=TrainingArguments(
        output_dir=OUTPUT_DIR,
        per_device_train_batch_size=2,
        gradient_accumulation_steps=4,
        warmup_steps=10,
        num_train_epochs=3,
        learning_rate=2e-4,
        fp16=True,
        logging_steps=10,
        save_strategy="epoch",
        optim="adamw_8bit",
        report_to="none",
    ),
)

trainer.train()
model.save_pretrained(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)
print(f"[unsloth] LoRA adapter saved to {{OUTPUT_DIR}}")
'''

_EXPORT_SCRIPT = '''\
#!/usr/bin/env bash
# Generated by train_lora.py
# Converts the LoRA adapter to a quantized GGUF and loads it into Ollama.
# Requires: pip install llama-cpp-python
set -euo pipefail

LORA_DIR="{lora_dir}"
MODELFILE="{modelfile_path}"
GGUF_OUT="{gguf_out}"

echo "[export] converting LoRA adapter to q4_k_m GGUF..."
python3 -m llama_cpp.convert "$LORA_DIR" --outtype q4_k_m --outfile "$GGUF_OUT"

echo "[export] creating loci-tuned in Ollama..."
ollama create loci-tuned -f "$MODELFILE"

echo "[export] done. Run: ollama run loci-tuned"
'''

_EXPORT_MODELFILE = '''\
FROM {gguf_out}
SYSTEM You are Loci, an autonomous coding agent with strong memory. You learn from past failures and apply corrected reasoning.
'''


def run_unsloth_backend(args: argparse.Namespace) -> None:
    lora_dir = os.path.join(_HERE, "loci-lora")
    gguf_out = os.path.join(_HERE, "loci-lora", "loci-tuned.q4_k_m.gguf")
    modelfile_path = os.path.join(_HERE, "Modelfile")
    unsloth_script_path = os.path.join(_HERE, "run_unsloth.py")
    export_script_path = os.path.join(_HERE, "export_gguf.sh")

    sft_abs = os.path.abspath(args.sft)

    unsloth_content = _UNSLOTH_SCRIPT.format(
        sft_path=sft_abs,
        base_model="unsloth/llama-3.2-3b-instruct",
        output_dir=lora_dir,
    )
    with open(unsloth_script_path, "w") as f:
        f.write(unsloth_content)

    modelfile_content = _EXPORT_MODELFILE.format(gguf_out=gguf_out)
    with open(modelfile_path, "w") as f:
        f.write(modelfile_content)

    export_content = _EXPORT_SCRIPT.format(
        lora_dir=lora_dir,
        modelfile_path=modelfile_path,
        gguf_out=gguf_out,
    )
    with open(export_script_path, "w") as f:
        f.write(export_content)
    os.chmod(export_script_path, 0o755)

    print(f"[train] emitted → {unsloth_script_path}")
    print(f"[train] emitted → {export_script_path}")
    print(f"[train] emitted → {modelfile_path}")
    print()
    print(textwrap.dedent("""\
        [train] Next steps (GPU machine required):
          1.  pip install unsloth trl transformers datasets bitsandbytes
          2.  python3 mlops/finetune/run_unsloth.py
          3.  bash mlops/finetune/export_gguf.sh
          4.  ollama run loci-tuned
    """))


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Fine-tune or bake Ollama model on SFT pairs")
    p.add_argument("--sft", required=True, help="Path to sft_pairs.jsonl")
    p.add_argument("--base-model", default="llama3.2:latest",
                   help="Ollama model tag to use as the base")
    p.add_argument("--backend", choices=["ollama-modelfile", "unsloth"],
                   default="ollama-modelfile",
                   help="Training backend (default: ollama-modelfile)")
    p.add_argument("--max-examples", type=int, default=200,
                   help="Cap on how many SFT pairs to include (ollama-modelfile only)")
    return p.parse_args()


def main() -> None:
    args = parse_args()

    if args.backend == "ollama-modelfile":
        run_ollama_modelfile_backend(args)
    elif args.backend == "unsloth":
        run_unsloth_backend(args)


if __name__ == "__main__":
    main()
