#!/usr/bin/env python3
"""
a2a_watchdog.py — Health check + WSL portproxy maintenance for the Hermes A2A server.

Two jobs in one:
1. Health-check the A2A server; restart via systemd if down.
2. Check that the WSL IP in the Windows portproxy rule matches the current eth0 IP.
   If it drifted (WSL restarted), write an updated portproxy script to C:\\tmp\\ and
   alert so the operator can run it elevated. Cannot self-apply because netsh requires Admin.

Silent on healthy (no output = no cron delivery). Prints only on problems.

Env vars:
  HERMES_A2A_HEALTH_URL  Health check URL (default: http://127.0.0.1:8201/health)
  HERMES_A2A_SERVICE     systemd user service name (default: hermes-a2a.service)
  HERMES_TAILSCALE_IP    Tailscale IP for portproxy rule (required if using portproxy check)
  HERMES_A2A_PORT        A2A server port (default: 8201)
  HERMES_PORTPROXY_PS1   Output path for the portproxy script (default: /mnt/c/tmp/hermes-a2a-portproxy.ps1)
"""
import subprocess
import sys
import json
import urllib.request
import urllib.error
import socket
import os
import re
from pathlib import Path

HEALTH_URL    = os.environ.get("HERMES_A2A_HEALTH_URL", "http://127.0.0.1:8201/health")
SERVICE       = os.environ.get("HERMES_A2A_SERVICE", "hermes-a2a.service")
TAILSCALE_IP  = os.environ.get("HERMES_TAILSCALE_IP", "<your-tailscale-ip>")
A2A_PORT      = int(os.environ.get("HERMES_A2A_PORT", "8201"))
PORTPROXY_PS1 = os.environ.get("HERMES_PORTPROXY_PS1", "/mnt/c/tmp/hermes-a2a-portproxy.ps1")
STATE_FILE    = Path.home() / ".hermes-a2a-watchdog-state.json"


def load_state():
    try:
        return json.loads(STATE_FILE.read_text())
    except Exception:
        return {}


def save_state(state):
    STATE_FILE.write_text(json.dumps(state, indent=2))


def check_health():
    try:
        with urllib.request.urlopen(HEALTH_URL, timeout=5) as r:
            return r.status == 200
    except Exception:
        return False


def get_wsl_ip():
    try:
        result = subprocess.run(
            ["ip", "addr", "show", "eth0"],
            capture_output=True, text=True, timeout=5
        )
        m = re.search(r"inet (\d+\.\d+\.\d+\.\d+)/", result.stdout)
        return m.group(1) if m else None
    except Exception:
        return None


def get_portproxy_wsl_ip():
    """Read current portproxy rule for our port from Windows via PowerShell."""
    try:
        result = subprocess.run(
            ["powershell.exe", "-Command",
             f"netsh interface portproxy show v4tov4 | Select-String '{A2A_PORT}'"],
            capture_output=True, text=True, timeout=10
        )
        m = re.search(rf"{re.escape(TAILSCALE_IP)}\s+{A2A_PORT}\s+(\d+\.\d+\.\d+\.\d+)", result.stdout)
        return m.group(1) if m else None
    except Exception:
        return None


def write_portproxy_script(wsl_ip):
    content = f"""# hermes-a2a-portproxy.ps1 (auto-regenerated by a2a_watchdog.py)
# Forwards Tailscale IP {TAILSCALE_IP}:{A2A_PORT} -> WSL {wsl_ip}:{A2A_PORT}
# Run as Administrator.

$TailscaleIP = "{TAILSCALE_IP}"
$WslIP       = "{wsl_ip}"
$Port        = {A2A_PORT}

netsh interface portproxy delete v4tov4 listenaddress=$TailscaleIP listenport=$Port 2>$null
netsh interface portproxy add v4tov4 `
    listenaddress=$TailscaleIP `
    listenport=$Port `
    connectaddress=$WslIP `
    connectport=$Port

$ruleName = "Hermes A2A Server ({A2A_PORT})"
netsh advfirewall firewall delete rule name="$ruleName" 2>$null
netsh advfirewall firewall add rule `
    name="$ruleName" dir=in action=allow protocol=TCP `
    localport=$Port localip=$TailscaleIP `
    description="Hermes A2A server accessible over Tailscale mesh"

Write-Host "Portproxy updated: ${{TailscaleIP}}:${{Port}} -> ${{WslIP}}:${{Port}}"
"""
    try:
        Path(PORTPROXY_PS1).write_text(content)
        return True
    except Exception:
        return False


def restart_service():
    r = subprocess.run(
        ["systemctl", "--user", "restart", SERVICE],
        capture_output=True, text=True
    )
    return r.returncode == 0


alerts = []
state = load_state()

# ── 1. Health check ──────────────────────────────────────────────────────────
if not check_health():
    import time
    restarted = restart_service()
    time.sleep(3)
    back_up = check_health()
    if back_up:
        alerts.append(f"{SERVICE} was down — restarted via systemd, now healthy.")
    else:
        alerts.append(f"{SERVICE} is DOWN and failed to restart.")
        alerts.append(f"  Check: systemctl --user status {SERVICE}")
        alerts.append(f"  Logs:  journalctl --user -u {SERVICE} -n 50")

# ── 2. Portproxy IP drift check ──────────────────────────────────────────────
wsl_ip = get_wsl_ip()
proxy_ip = get_portproxy_wsl_ip()
last_known_wsl_ip = state.get("wsl_ip")

if wsl_ip and proxy_ip and wsl_ip != proxy_ip:
    # WSL IP drifted — update the script and alert
    written = write_portproxy_script(wsl_ip)
    alerts.append(f"WSL IP changed: {proxy_ip} -> {wsl_ip}")
    alerts.append(f"Portproxy rule is stale. Updated script written to {PORTPROXY_PS1}")
    alerts.append(f"Run elevated: powershell -ExecutionPolicy Bypass -File {PORTPROXY_PS1}")
elif wsl_ip and not proxy_ip:
    # No portproxy rule at all
    written = write_portproxy_script(wsl_ip)
    alerts.append(f"No portproxy rule found for port {A2A_PORT}.")
    alerts.append(f"Script written to {PORTPROXY_PS1} — run elevated to apply.")

if wsl_ip:
    state["wsl_ip"] = wsl_ip
    save_state(state)

# ── Output ───────────────────────────────────────────────────────────────────
if alerts:
    print("\n".join(alerts))
# else: silent — no output, no delivery
