#!/usr/bin/env python3
"""Build the curated `MEMORY.md` index from memory files.

This replaces hand-maintained `MEMORY.md`, which fails in two ways: manual
trimming does not hold, and flat hand-edited lists silently orphan files they
forget to link.

The script derives the index from the memory files and enforces the budget
structurally, so the generated output cannot exceed it.

The budget has two axes because the reader truncates on both:
- `--budget-chars` is met by shortening hooks.
- `--budget-lines` cannot be met by shortening hooks alone because the generator
  still emits one line per memory file. Growing stores otherwise shave hooks
  into stubs while line count escapes the reader window. To bound lines, the
  script rolls whole sections into generated `wiki-<section>.md` topic indexes,
  leaving one pointer line behind.
- `--keep-inline` names sections that must never roll out (standing rules read
  every session).
- Rolled entries keep their full hook in the hub, so rollup restores detail the
  char budget had already shaved away.

Usage:
    scripts/generate_memory_index.py [memory_dir] [--budget-chars N] [--budget-lines N]
                                      [--keep-inline "A,B"] [--source PATH]
                                      [--headroom-pct N] [--dry-run] [--check]

`memory_dir` defaults to `backends.memory_dir()`, which resolves in order:
`LOCI_MEMORY_MD_DIR` -> gitignored config `[memory].dir` -> `LOCI_MEMORY_DIR`
-> `HERMES_MEMORY_DIR` -> `''` (unconfigured). No host-specific path is hardcoded.

`--source` defaults to `<memory_dir>/MEMORY.md` when it exists so the default
run preserves the current section grouping instead of collapsing to
`metadata.type` buckets.

Output: `<memory_dir>/MEMORY.md`. Existing files are backed up first as
`MEMORY.md.bak-YYYYMMDD-HHMMSS-ffffff` unless `--dry-run`. `--headroom-pct`
(default 5) targets generation below `--budget-chars` so a manual edit between
runs does not immediately re-overflow.

Nothing currently wires this script into a schedule or CI. `--check` exits
non-zero when the on-disk index has drifted from regenerated output without
writing; wire that into cron or pre-commit to make the structural guarantee real.
"""
from __future__ import annotations

import argparse
import datetime
import os
import re
import shutil
import sys
from pathlib import Path

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "mcp"))

DEFAULT_BUDGET_CHARS = 24986  # 24.4 KiB, measured in characters — see [m1]
DEFAULT_BUDGET_LINES = 150  # the reader truncates on LINES, independently of chars — see [m2]
DEFAULT_HEADROOM_PCT = 5.0
ELLIPSIS = "…"
_FRONTMATTER_KEY_RE = re.compile(r'^([A-Za-z_][\w-]*):\s*(.*)$')
_SECTION_RE = re.compile(r'^##\s+(.+?)\s*$')
_LINK_RE = re.compile(r'\(([\w./\-]+\.md)\)')
_WORKING_AGREEMENTS_SECTION = "Working agreements"
_MARKER_WARNING = "⚠"  # ⚠ — entries carrying this keep more of their hook under truncation
_MARKER_STATUS = "✅"   # ✅

# [m2] Char budget alone cannot bound line count: this generator emits one
# line per memory file and only shortens hooks. A growing store can hit the char
# cap by shaving hooks into stubs while still overflowing the reader's ~200-line
# window. Bounding lines needs a structural lever: roll whole sections into
# generated topic-index ("hub") files and leave one pointer line behind.
HUB_PREFIX = "wiki-"
HUB_SECTION = "Topic indexes"
# Sections that must stay inline regardless of budget: they are read every
# session and are behavioural, not referential. Rolling them into a hub would
# hide standing rules behind a second read.
DEFAULT_KEEP_INLINE = (_WORKING_AGREEMENTS_SECTION, "Feedback")
_HUB_GENERATED_MARKER = "<!-- generated by generate_memory_index.py -->"


def hub_filename(section: str) -> str:
    """Stable, filesystem-safe hub name for a section title."""
    slug = re.sub(r'[^a-z0-9]+', '-', section.lower()).strip('-')
    return f"{HUB_PREFIX}{slug or 'other'}.md"


def resolve_memory_dir(cli_arg: str | None) -> str | None:
    if cli_arg:
        return cli_arg
    try:
        import backends
        return backends.memory_dir() or None
    except Exception as exc:
        print(f"[generate_memory_index] backends.memory_dir() unavailable: {exc}", file=sys.stderr)
        return None


def _unquote(v: str) -> str:
    v = v.strip()
    if len(v) >= 2 and v[0] == v[-1] and v[0] in "\"'":
        return v[1:-1]
    return v


def parse_frontmatter(text: str) -> tuple[dict, str | None]:
    """Pull `name` / `description` / `metadata.type` from a `---` YAML-ish block.

    Never raises. Returns `(fields, error)`. On malformed input, `error` is set
    and `fields` still contain whatever could be recovered, so broken files are
    reported instead of skipped.
    """
    fields: dict = {"name": None, "description": None, "type": None}
    start = text.find("---")
    if start == -1 or text[:start].strip():
        return fields, "no leading frontmatter delimiter"
    end = text.find("\n---", start + 3)
    if end == -1:
        return fields, "unterminated frontmatter block (no closing ---)"
    block = text[start + 3:end]

    in_metadata = False
    for raw in block.splitlines():
        if not raw.strip():
            continue
        indent = len(raw) - len(raw.lstrip(" "))
        line = raw.strip()
        m = _FRONTMATTER_KEY_RE.match(line)
        if indent == 0:
            if not m:
                continue
            key, val = m.group(1), _unquote(m.group(2))
            if key == "metadata":
                in_metadata = True
                continue
            in_metadata = False
            if key in fields:
                fields[key] = val or None
        elif in_metadata and m and m.group(1) == "type":
            fields["type"] = _unquote(m.group(2)) or None

    errors = [f"missing '{k}'" for k in ("name", "description") if not fields.get(k)]
    return fields, "; ".join(errors) if errors else None


class Entry:
    __slots__ = ("filename", "title", "hook", "mtype", "error")

    def __init__(self, filename: str, title: str, hook: str, mtype: str | None, error: str | None):
        self.filename = filename
        self.title = title
        self.hook = hook
        self.mtype = mtype
        self.error = error


def _title_from(name: str | None, path: Path) -> str:
    raw = name or path.stem
    return raw.replace("-", " ").replace("_", " ").strip()


def load_entries(memory_dir: Path) -> tuple[list[Entry], list[tuple[str, str]]]:
    # Hub files are generated output, not source memories. Indexing them would
    # add one entry per hub next run and could re-roll hub contents into another
    # hub: the generator eating its own output.
    files = sorted(p for p in memory_dir.glob("*.md")
                   if p.name != "MEMORY.md" and not p.name.startswith(HUB_PREFIX))
    entries: list[Entry] = []
    malformed: list[tuple[str, str]] = []
    for p in files:
        try:
            text = p.read_text(encoding="utf-8", errors="replace")
        except OSError as exc:
            err = str(exc)
            malformed.append((p.name, err))
            print(f"[generate_memory_index] WARNING: {p.name}: unreadable: {err}", file=sys.stderr)
            entries.append(Entry(p.name, _title_from(None, p), f"(unreadable: {err})", None, err))
            continue
        fields, err = parse_frontmatter(text)
        if err:
            malformed.append((p.name, err))
            print(f"[generate_memory_index] WARNING: {p.name}: {err}", file=sys.stderr)
        title = _title_from(fields.get("name"), p)
        hook = fields.get("description") or ""
        if err:
            note = f"(frontmatter: {err})"
            hook = f"{hook} {note}".strip() if hook else note
        entries.append(Entry(p.name, title, hook, fields.get("type"), err))
    return entries, malformed


_CURATED_RE = re.compile(
    r'^-\s*\[(?P<title>[^\]]*)\]\((?P<file>[\w./\-]+\.md)\)\s*(?:\u2014\s*(?P<hook>.*))?$')


def parse_source_sections(
        text: str) -> tuple[list[str], dict[str, list[str]], dict[str, tuple[str, str]]]:
    """Recover `'## Section' -> [filenames]` from an existing index, in order.

    Also recover each entry's curated title and hook. Curated hooks are hand-
    written and preserve markers and shorthand that frontmatter descriptions do
    not, so they are the better source for rendered index lines.
    """
    order: list[str] = []
    sections: dict[str, list[str]] = {}
    curated: dict[str, tuple[str, str]] = {}
    current: str | None = None
    for line in text.splitlines():
        h = _SECTION_RE.match(line)
        if h:
            current = h.group(1).strip()
            if current not in sections:
                sections[current] = []
                order.append(current)
            continue
        if current is None:
            continue
        m = _LINK_RE.search(line)
        if m:
            sections[current].append(m.group(1))
            c = _CURATED_RE.match(line.strip())
            if c:
                curated[c.group("file")] = (
                    (c.group("title") or "").strip(), (c.group("hook") or "").strip())
    return order, sections, curated


def _type_section_name(mtype: str | None) -> str:
    if not mtype:
        return "Other"
    return mtype.replace("_", " ").replace("-", " ").title()


def apply_curated(entries: list[Entry],
                  curated: dict[str, tuple[str, str]]) -> list[Entry]:
    """Prefer curated titles/hooks from the source index over frontmatter text.

    Curated lines carry operator markers and shorthand; frontmatter descriptions
    serve a different purpose. Files never listed in the index keep their
    description, and curated links outside the memory dir are preserved instead
    of dropped.
    """
    if not curated:
        return entries
    by_file = {e.filename: e for e in entries}
    for fname, (ctitle, chook) in curated.items():
        e = by_file.get(fname)
        if e is None:
            if "/" in fname:
                entries.append(Entry(fname, ctitle or fname, chook, None, None))
            continue
        if ctitle:
            e.title = ctitle
        if chook and not e.error:
            # A curated hook ending in the ellipsis is this generator's own
            # truncated output, not operator prose. Preferring it makes truncation
            # cumulative and irreversible, so fall back to the never-truncated
            # frontmatter description instead.
            if chook.endswith(ELLIPSIS) and e.hook:
                continue
            e.hook = chook
    return entries


def build_sections(entries: list[Entry], source_order: list[str],
                    source_sections: dict[str, list[str]]) -> dict[str, list[Entry]]:
    """Keep source-index grouping for still-listed files; group the rest by `metadata.type`."""
    by_file = {e.filename: e for e in entries}
    used: set[str] = set()
    result: dict[str, list[Entry]] = {}

    for section in source_order:
        bucket = [by_file[f] for f in source_sections[section] if f in by_file and f not in used]
        used.update(e.filename for e in bucket)
        if bucket:
            result[section] = bucket

    remaining = [e for e in entries if e.filename not in used]
    by_type: dict[str, list[Entry]] = {}
    for e in remaining:
        by_type.setdefault(_type_section_name(e.mtype), []).append(e)
    for section in sorted(by_type):
        by_type[section].sort(key=lambda e: e.filename)
        # Append, do not assign: a type-derived section can collide with an
        # existing source section, and assignment would drop earlier members.
        result.setdefault(section, []).extend(by_type[section])

    return result


def _render_line(e: Entry) -> str:
    if e.hook:
        return f"- [{e.title}]({e.filename}) — {e.hook}"
    return f"- [{e.title}]({e.filename})"


def render(sections: dict[str, list[Entry]]) -> str:
    lines = ["# Memory index", ""]
    for section, ents in sections.items():
        lines.append(f"## {section}")
        for e in ents:
            lines.append(_render_line(e))
        lines.append("")
    text = "\n".join(lines)
    while text.endswith("\n\n"):
        text = text[:-1]
    return text if text.endswith("\n") else text + "\n"


def line_count(text: str) -> int:
    return text.count("\n")


def _hub_pointer(section: str, ents: list[Entry], preview: int = 4) -> Entry:
    """Build the one pointer line a rolled-up section leaves in `MEMORY.md`.

    It names a few members so the pointer is searchable by content, not just by
    heading; a grep for `kinect` should still tell the agent where to look.
    """
    shown = " · ".join(e.title for e in ents[:preview])
    hook = f"{len(ents)} memories: {shown}"
    if len(ents) > preview:
        hook += " · …"
    return Entry(hub_filename(section), section, hook, "reference", None)


def inline_view(sections: dict[str, list[Entry]],
                rolled: list[str]) -> dict[str, list[Entry]]:
    """Return what `MEMORY.md` renders: inline sections plus one pointer per rollup."""
    out: dict[str, list[Entry]] = {
        name: list(ents) for name, ents in sections.items() if name not in rolled}
    if rolled:
        out[HUB_SECTION] = [_hub_pointer(n, sections[n]) for n in rolled]
    return out


def plan_rollups(sections: dict[str, list[Entry]], budget_lines: int,
                 keep_inline: tuple[str, ...] | set[str]) -> list[str]:
    """Choose the fewest section rollups needed to meet the line budget.

    Roll largest sections first: each rollup trades `N` lines for `1`, so the
    biggest section buys the most room per pointer spent. Protected sections are
    never candidates. If even rolling everything else is insufficient, return the
    best effort rather than hide standing rules.
    """
    protected = set(keep_inline)
    rolled: list[str] = []
    while line_count(render(inline_view(sections, rolled))) > budget_lines:
        candidates = [s for s in sections if s not in protected and s not in rolled]
        if not candidates:
            return rolled
        candidates.sort(key=lambda s: (-len(sections[s]), s))
        rolled.append(candidates[0])
    return rolled


def render_hub(section: str, ents: list[Entry]) -> str:
    """Render a rolled-up section as a standalone memory file.

    The file keeps a `## <section>` listing so `parse_source_sections()` can
    recover grouping next run, and it preserves full hooks because only
    `MEMORY.md` is budgeted.
    """
    stem = hub_filename(section)[:-3]
    lines = [
        "---",
        f"name: {stem}",
        f"description: \"Topic index — {section}: {len(ents)} memories, rolled out of "
        f"MEMORY.md to keep it inside the reader line budget.\"",
        "metadata:",
        "  type: reference",
        "---",
        "",
        _HUB_GENERATED_MARKER,
        f"# {section}",
        "",
        f"{len(ents)} memories. Generated by `scripts/generate_memory_index.py`; do not",
        "hand-edit. Edit the topic file's frontmatter, or its line below, and let the next",
        "run regenerate. Hooks here are full text — the line budget truncates MEMORY.md,",
        "not this file.",
        "",
        f"## {section}",
    ]
    lines.extend(_render_line(e) for e in ents)
    lines.append("")
    return "\n".join(lines)


def _boundary_cut(hook: str, limit: int) -> str:
    """Cut `hook` to `limit` chars without splitting obvious boundaries.

    Prefer word/clause boundaries and never leave unbalanced backticks, so an
    identifier/path/PR number already inside the limit is not cut in half.
    """
    candidate = hook[:limit]
    if candidate.count("`") % 2 == 1:
        last_tick = candidate.rfind("`")
        if last_tick > 0:
            candidate = candidate[:last_tick]
    if candidate and not candidate[-1].isspace():
        window = max(0, len(candidate) - 40)
        for i in range(len(candidate) - 1, window - 1, -1):
            if candidate[i] in " ,;:":
                candidate = candidate[:i]
                break
    return candidate


def _truncate_hook(hook: str, allowance: int) -> str:
    if len(hook) <= allowance:
        return hook
    if allowance <= 0:
        return ""
    if allowance == 1:
        return hook[:1]
    return _boundary_cut(hook, allowance - 1).rstrip() + ELLIPSIS


def _entry_weight(section: str, hook: str) -> float:
    """Assign more truncation budget to warning/status markers and curated agreements."""
    weight = 1.0
    if _MARKER_WARNING in hook:
        weight += 2.0
    if _MARKER_STATUS in hook:
        weight += 1.0
    if section == _WORKING_AGREEMENTS_SECTION:
        weight += 1.0
    return weight


def fit_to_budget(sections: dict[str, list[Entry]], budget_chars: int) -> bool:
    """Shorten hooks to fit while preserving the most valuable entries longest.

    Weight each hook's allowance by salience (warning/status markers and the
    `Working agreements` section), never touching titles or links. Binary-search
    a scale factor over a real render, so the hard budget is still guaranteed.
    Return `False` only when the budget fails even with every hook emptied.
    """
    entries = [e for ents in sections.values() for e in ents]
    original = {id(e): e.hook for e in entries}
    weight = {id(e): _entry_weight(section, original[id(e)])
              for section, ents in sections.items() for e in ents}

    def apply(scale: int) -> None:
        for e in entries:
            allowance = min(len(original[id(e)]), max(0, round(scale * weight[id(e)])))
            e.hook = _truncate_hook(original[id(e)], allowance)

    def fits(scale: int) -> bool:
        apply(scale)
        return len(render(sections)) <= budget_chars

    if not fits(0):
        return False

    hi = max((len(h) for h in original.values()), default=0)
    lo, best = 0, 0
    while lo <= hi:
        mid = (lo + hi) // 2
        if fits(mid):
            best = mid
            lo = mid + 1
        else:
            hi = mid - 1
    apply(best)
    return True


def _apply_headroom(budget_chars: int, headroom_pct: float) -> int:
    if headroom_pct <= 0:
        return budget_chars
    return max(0, int(budget_chars * (1 - headroom_pct / 100.0)))


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                  formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("memory_dir", nargs="?", default=None,
                     help="directory of memory files (default: backends.memory_dir())")
    ap.add_argument("--budget-chars", type=int, default=DEFAULT_BUDGET_CHARS,
                     help=f"hard char budget for the generated index (default {DEFAULT_BUDGET_CHARS})")
    ap.add_argument("--source", default=None,
                     help="existing index to read '## Section' grouping from "
                          "(default: <memory_dir>/MEMORY.md, if it exists)")
    ap.add_argument("--budget-lines", type=int, default=DEFAULT_BUDGET_LINES,
                     help=f"max lines in the generated index; sections over it are rolled "
                          f"into {HUB_PREFIX}*.md topic files (default {DEFAULT_BUDGET_LINES})")
    ap.add_argument("--keep-inline", default=",".join(DEFAULT_KEEP_INLINE),
                     help="comma-separated sections never rolled into a hub "
                          f"(default: {', '.join(DEFAULT_KEEP_INLINE)})")
    ap.add_argument("--headroom-pct", type=float, default=DEFAULT_HEADROOM_PCT,
                     help=f"target this %% below --budget-chars, leaving room for a manual "
                          f"edit before the next run (default {DEFAULT_HEADROOM_PCT})")
    ap.add_argument("--dry-run", action="store_true", help="print to stdout, write nothing")
    ap.add_argument("--check", action="store_true",
                     help="exit non-zero if the on-disk index has drifted from what "
                          "regeneration would produce; writes nothing")
    args = ap.parse_args(argv)

    memory_dir_str = resolve_memory_dir(args.memory_dir)
    if not memory_dir_str:
        print("error: no memory directory given and none configured "
              "(pass one, or set LOCI_MEMORY_MD_DIR / [memory].dir / "
              "LOCI_MEMORY_DIR / HERMES_MEMORY_DIR)",
              file=sys.stderr)
        return 2
    d = Path(memory_dir_str)
    if not d.is_dir():
        print(f"error: memory dir not found: {d}", file=sys.stderr)
        return 2

    entries, malformed = load_entries(d)
    if not entries:
        print(f"error: no memory files found in {d}", file=sys.stderr)
        return 2

    out_path = d / "MEMORY.md"
    source_path = args.source
    if source_path is None and out_path.exists():
        source_path = str(out_path)

    source_order: list[str] = []
    source_sections: dict[str, list[str]] = {}
    curated: dict[str, tuple[str, str]] = {}

    def absorb(text: str) -> None:
        order, secs, cur = parse_source_sections(text)
        for name in order:
            if name not in source_sections:
                source_sections[name] = []
                source_order.append(name)
            for f in secs[name]:
                if f not in source_sections[name]:
                    source_sections[name].append(f)
        for k, v in cur.items():
            curated.setdefault(k, v)

    if source_path:
        sp = Path(source_path)
        if sp.exists():
            absorb(sp.read_text(encoding="utf-8", errors="replace"))
        else:
            print(f"[generate_memory_index] WARNING: --source {sp} not found; "
                  f"grouping by metadata.type instead", file=sys.stderr)
    # Existing hubs are part of grouping state, not a separate store. Once a
    # section rolls out, `MEMORY.md` stops listing its files, so skipping hubs here
    # would scatter them into `metadata.type` buckets next run. Absorb `MEMORY.md`
    # first so its ordering wins.
    for hp in sorted(d.glob(f"{HUB_PREFIX}*.md")):
        absorb(hp.read_text(encoding="utf-8", errors="replace"))

    entries = apply_curated(entries, curated)

    for e in entries:
        if "/" in e.filename and not (d / e.filename).exists():
            print(f"[generate_memory_index] WARNING: {e.filename}: link does not resolve "
                  f"from {d}", file=sys.stderr)

    sections = build_sections(entries, source_order, source_sections)

    keep_inline = tuple(s.strip() for s in args.keep_inline.split(",") if s.strip())
    rolled = plan_rollups(sections, args.budget_lines, keep_inline)
    # Render before `fit_to_budget`, which mutates hooks in place; hubs are not
    # budgeted and must keep full text.
    hubs = {hub_filename(name): render_hub(name, sections[name]) for name in rolled}
    inline = inline_view(sections, rolled)

    target_budget = _apply_headroom(args.budget_chars, args.headroom_pct)
    if not fit_to_budget(inline, target_budget):
        print(f"error: cannot fit {len(entries)} entries within --budget-chars={args.budget_chars} "
              f"(target {target_budget} after --headroom-pct={args.headroom_pct}) "
              f"even with every hook emptied — raise the budget or reduce the memory count",
              file=sys.stderr)
        return 3

    doc = render(inline)
    if line_count(doc) > args.budget_lines:
        # Reached only when protected sections alone overflow and `plan_rollups`
        # has nothing left it may move. Warn instead of failing: a long index still
        # loads partially, while a non-zero exit would leave the older index in place.
        print(f"[generate_memory_index] WARNING: index is {line_count(doc)} lines, over "
              f"--budget-lines={args.budget_lines}; sections kept inline "
              f"({', '.join(keep_inline)}) already exceed it. Split one, or lower "
              f"--keep-inline.", file=sys.stderr)
    if len(doc) > args.budget_chars:
        # `fit_to_budget()` already guarantees this. A mismatch means `render()`
        # is non-deterministic, which is a bug, not a soft failure.
        print(f"error: generated index is {len(doc)} chars, over budget {args.budget_chars}",
              file=sys.stderr)
        return 3

    print(f"[generate_memory_index] {len(entries)} memory files indexed "
          f"({len(malformed)} flagged: malformed/missing frontmatter), "
          f"{len(doc)} chars (budget {args.budget_chars}, target {target_budget}), "
          f"{line_count(doc)} lines (budget {args.budget_lines}), "
          f"{len(rolled)} section(s) rolled into hubs"
          f"{': ' + ', '.join(rolled) if rolled else ''}", file=sys.stderr)

    if args.check:
        stale = []
        if (out_path.read_text(encoding="utf-8") if out_path.exists() else None) != doc:
            stale.append(out_path.name)
        # A drifted hub is as stale as a drifted index: it holds entries no
        # longer listed in `MEMORY.md`, so skipping it would let `--check` go green
        # on content the rollup hid.
        for fname, text in hubs.items():
            hp = d / fname
            if (hp.read_text(encoding="utf-8") if hp.exists() else None) != text:
                stale.append(fname)
        if stale:
            print(f"error: stale relative to source memory files: {', '.join(stale)} "
                  f"(run without --check to regenerate)", file=sys.stderr)
            return 4
        print(f"OK: {out_path} and {len(hubs)} hub file(s) up to date", file=sys.stderr)
        return 0

    if args.dry_run:
        print(doc)
        for fname, text in hubs.items():
            print(f"\n===== {fname} =====\n{text}")
        return 0

    if out_path.exists():
        stamp = datetime.datetime.now().strftime("%Y%m%d-%H%M%S-%f")
        backup = d / f"MEMORY.md.bak-{stamp}"
        shutil.copy2(out_path, backup)
        print(f"[generate_memory_index] backed up {out_path} -> {backup}", file=sys.stderr)
    for fname, text in hubs.items():
        (d / fname).write_text(text, encoding="utf-8")
    # A hub for a section that no longer rolls up would keep reseeding grouping
    # from a stale member list, so retire hubs we did not just write. Touch only
    # files carrying this generator's marker.
    for hp in sorted(d.glob(f"{HUB_PREFIX}*.md")):
        if hp.name not in hubs and _HUB_GENERATED_MARKER in hp.read_text(
                encoding="utf-8", errors="replace"):
            hp.unlink()
            print(f"[generate_memory_index] retired stale hub {hp.name}", file=sys.stderr)
    out_path.write_text(doc, encoding="utf-8")
    print(f"OK: {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
